services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: isa
      POSTGRES_PASSWORD: isa
      POSTGRES_DB: jutjubic
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U isa -d jutjubic"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api1:
    build: ./backend
    environment:
      PORT: 5000
      INSTANCE_NAME: api-1
      DATABASE_URL: postgres://isa:isa@db:5432/jutjubic
      JWT_SECRET: yoursecret
      FRONTEND_URL: http://localhost:3000
      # EMAIL_USER / EMAIL_PASS po potrebi
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health/live | grep -q '\"status\":\"live\"'"]
      interval: 5s
      timeout: 3s
      retries: 10

  api2:
    build: ./backend
    environment:
      PORT: 5000
      INSTANCE_NAME: api-2
      DATABASE_URL: postgres://isa:isa@db:5432/jutjubic
      JWT_SECRET: yoursecret
      FRONTEND_URL: http://localhost:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health/live | grep -q '\"status\":\"live\"'"]
      interval: 5s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"     # spolja 5000, unutra nginx 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
